name: Tests and Deploy on Heroku

on: [pull_request]

jobs:
  HerokuDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: docker build . -t node_app && docker run node_app npm run test
      - name: Build
        run: npm i && npm run build